### ISSUE TITLE
Progress indicator of installer gets stuck when we run into an error

### ISSUE THREAD

**Issue by DominikTo** [fruux/sabre-katana#101]
![screen shot 2015-03-23 at 13 29 56](https://cloud.githubusercontent.com/assets/1384635/6779913/d810d24a-d160-11e4-8ab9-446ea8aaa772.png)

**Comment by Hywan** [comment]
I am thinking about closing this issue and reopen if someone met other errors than the one we already detect. Feel free to reply!
