### ISSUE TITLE
Browser feature detection

### ISSUE THREAD

**Issue by evert** [fruux/sabre-katana#145]
We should add some detection scripts to see if the users browser can support the installer and/or admin interface.

Right now we can at least detect EventSource support, which already means IE10 and up.

**Comment by Hywan** [comment]
What browsers we would like to support?

**Comment by evert** [comment]
how about the last two versions of every major browser?

**Comment by Hywan** [comment]
Deal.

**Comment by Hywan** [comment]
This is really difficult to detect whether Ember, Semantic UI or jQuery can run safely. So, I hate doing this, but instead of detecting features, we have to sniff the browser :-/.
