### ISSUE TITLE
composer.lock?

### ISSUE THREAD

**Issue by Grummfy** [fruux/sabre-katana#152]
Hello,
why not adding composer.lock in the repository?

Why ?
Simply because with this lock file you  are certain that the people that clone this repository will have the exact same version of the externals libs. This assure that test that fails will  fails, bug are reproductible (in most of the case), ...

Some resources about this subject that have a lot more argument on this topics :
https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file
https://philsturgeon.uk/php/2014/11/04/composer-its-almost-always-about-the-lock-file/

**Comment by evert** [comment]
I agree. I think it's a good habit to commit 'composer.lock' for projects (and not libraries)

**Comment by Hywan** [comment]
Thanks :-).
