### ISSUE TITLE
Deleting a user/principal does not delete all calendars data

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-katana#155]
When we delete a principal, it is deleted from the `principals` and `users` tables, but no from `calendars`, `calendarchanges` and `calendarobjects` tables.

Is it a bug from sabre/dav or should we support it in sabre/katana? /cc @evert

**Comment by Hywan** [comment]
Confirmed by @DominikTo that we must hard delete a principal, not soft delete.

**Comment by evert** [comment]
Frankly I'm not sure yet how to approach this issue in sabre/dav. I think it's good to have it solved in sabre/katana until we figure it out =)

**Comment by Hywan** [comment]
:smile:
