### ISSUE TITLE
Little problem on display server address

### ISSUE THREAD

**Issue by vonglasow** [fruux/sabre-katana#162]
Chrome Version 41.0.2272.101 (64-bit)

![nxzw3](https://cloud.githubusercontent.com/assets/1275202/7301194/66be6c62-e9e1-11e4-8f88-7d537fdf3a49.jpg)

**Comment by Hywan** [comment]
Thanks, will try to reproduce tomorrow.

**Comment by Hywan** [comment]
I can reproduce.

**Comment by Hywan** [comment]
That's a CSS bug in Webkit, also present in Blink.

**Comment by Hywan** [comment]
I opened an issue on Semantic UI to see if they can do something: https://github.com/fruux/sabre-katana/issues/162.

**Comment by Hywan** [comment]
Fixed in https://github.com/Semantic-Org/Semantic-UI/releases/tag/1.12.1.
