### ISSUE TITLE
Better build system

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-katana#171]
We need a better build system: Separating server from client.

**Comment by evert** [comment]
I was also thinking about this a bit.. what if the admin is a separate composer or bower package?

**Comment by evert** [comment]
The admin interface in a perfect world only needs to be configured with a single server url =)

**Comment by Hywan** [comment]
The admin interface works on its own, nothing else is needed. It even automatically detect the base URL ;-).

**Comment by Hywan** [comment]
I guess the “admin interface is a separate composer or bower package” will be addressed in #173. This is a long run task, which also include #169 & co.

**Comment by Hywan** [comment]
#177 also introduces `make test`. I guess the build system is fine right now. I am closing this issue.
