### ISSUE TITLE
Ember map files missing

### ISSUE THREAD

**Issue by DominikTo** [fruux/sabre-katana#201]
404 in admin trying to load the following two map files:

* ember.min.map
* ember-template-compiler.map

**Comment by evert** [comment]
Note that these will only 404 if you open the inspector.

**Comment by Hywan** [comment]
This is Safari trying to load files on its own, it's not an error in Katana.

**Comment by DominikTo** [comment]
Thanks, also just found a similar "issue" in TryGhost/Ghost#5135.
