### ISSUE TITLE
Reorganize directory structure

### ISSUE THREAD

**Issue by evert** [fruux/sabre-katana#203]
In order for the update process to be relatively smoothly for the FTP users, I would like to be able to tell them the following:

1. Unzip
2. Overwrite every directory *except* the data directory.

To do this I would like to propose a simplified directory structure that looks a bit like this:

```
data/
data/db/
data/config/
data/log/
data/update/

resource/
resource/views/
resource/locale/
resource/webservices/ # webserver configuration files. Could also be called 'docs' or 'examples'
resource/sql/ # sql templates
```

This contains a very clear separation between the writable directory, and everything that is part of the package, and also reduces the complexity a bit, which is something me and @DominikTo ran into. 

This no longer contains "lost+found" though, but I don't think there was ever a real purpose.

If @DominikTo and @Hywan agrees, I would be happy to create the patch.

**Comment by evert** [comment]
Note that we _don't_ have to create a clean upgrade path for this yet. We can worry about that a bit later.

**Comment by DominikTo** [comment]
Simplified structure and more descriptive directory names: :+1: from me.

* `resource/` or resources/`?
* `foo/examples/` is better than `foo/webservices/`.

Only slightly related to this ticket:
* Should we also convert the config to a php file? Even if someone makes a config mistake (that makes the `data/` dir world readable) it would not be possible to gather db credentials from the file.

**Comment by evert** [comment]
resources make sense too =)

**Comment by Hywan** [comment]
Hey :-),

I like the idea but I wonder if it is really useful. So far, we can overwrite all files without peril. We only create 1 file: `data/etc/server.json`. If we unzip an archive, it won't overwrite this file because it does not exist in the archive, so no problem here. We also have the `data/variable/log/` directory, but same history here: They do no exist in the archive, so they are not going to be overwritten.

In fact, katana does not change anything from the source. So I wonder why it should be useful. The only think I understand is the desire to mimic the “classical” `data` directory from sabre/dav examples, am I right? It's not a good idea at all, but your proposal will require a big patch (no worry, we have tests to check regressions though).

After we answered this question and we adopt your proposal, then we have to discuss about the proposed architecture, it contains some issues too :-].

**Comment by Hywan** [comment]
(edited my previous comment, a big mistake in it :-p)

**Comment by evert** [comment]
The main benefit is that we can just tell people to upload the new version and skip the data directory. Some FTP clients might correctly 'merge' the changes from the old and the new, but I know at least a few that will fully overwrite the source directory.

By creating a clean separation between 'things that are part of the package and managed by source control' and 'things that are always changed by the user' we can avoid that issue a bit.

And both me and dominik just took some issue in general with the current directory structure. It felt a bit convoluted, but it wasn't really worth bringing up or changing... but now there's a real reason so it makes sense to me to take the extra step.

**Comment by Hywan** [comment]
Ok for your argument, but I am not confortable with your architecture proposition :-/.

Where the `lib/` directory goes? Where the `public/` directory goes? Why `views/` are now in `resources/`? What is a resource :-)?

**Comment by evert** [comment]
Keep `lib/` and `public/` the exact same.

I thought about moving views to `resource/`, just because the locale files are also there. It doesn't make sense to me that things like the locale files exist in a special directory, but stuff like `views/` exist in it's own root-level directory.

A "resource" in this case is similar to the "resource" in an apple app bundle:

https://developer.apple.com/library/ios/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html

> Resources are data files that live outside your application’s executable file. Resources typically consist of things like images, icons, sounds, nib files, strings files, configuration files, and data files (among others). Resource files can be localized for a particular language or region or shared by all localizations.
>
> The placement of resource files in the bundle directory structure depends on whether you are developing an iOS or Mac app. 

So, it's not an uncommon name for files like that.

**Comment by Hywan** [comment]
Ok for `resources/`. Plural or not? Long name or not (`db` vs. `database`).

I am a partisan of long names :-).

**Comment by evert** [comment]
I'm fine either way =)

**Comment by Hywan** [comment]
I am starting a patch :-).

**Comment by Hywan** [comment]
No, I have more tests to write before.

**Comment by Hywan** [comment]
Here is my proposal for the new architecture (very similar to @evert's proposal):
```
data
    configurations
    homes
    updates
    databases
    logs
resources
    views
    defaults
        databases
        http_servers
lib
public
tests
```

data/etc/locale will be deleted
data/lost+found will be deleted

**Comment by evert** [comment]
Sounds good to me, except I would make all the directory names in singular form, instead of plural

**Comment by Hywan** [comment]
So `datum` instead of `data`?

**Comment by Hywan** [comment]
And `test` instead of `tests`?

**Comment by evert** [comment]
No just the new directories. `datum` is never used in the english language btw.

**Comment by Hywan** [comment]
@evert: In American language* ;-). Ok. Here is the new proposal then:
```
data
    configuration
    home
    update
    database
    log
resource
    view
    default
        database
        http_server
lib
public
tests
```

**Comment by evert** [comment]
yep that looks great to me :+1:

**Comment by Hywan** [comment]
Patch under writing!
