### ISSUE TITLE
Reorder menu

### ISSUE THREAD

**Issue by DominikTo** [fruux/sabre-katana#209]
Current menu order is:

1. Calendars
2. Address books
3. Task lists

We should reorder it as:

1. Address books
2. Calendars
3. Task lists

**Comment by Hywan** [comment]
Why :stuck_out_tongue:?

**Comment by DominikTo** [comment]
Seems like a more 'natural' order. ;-)

**Comment by Hywan** [comment]
However, if we follow “CalDAV, CardDAV and WebDAV” order, we should have:

  1. Calendars,
  2. Task lists,
  3. Address books,
  4. Files.

Thoughts?

**Comment by DominikTo** [comment]
Usually, we also use this order: CardDAV, CalDAV and WebDAV.

**Comment by Hywan** [comment]
Ok for “CardDAV, CalDAV and WebDAV”.
