### ISSUE TITLE
Using home/end buttons in install script messes up input

### ISSUE THREAD

**Issue by evert** [fruux/sabre-katana#217]
When running `bin/katana install` I wanted to enter the base uri. I made a mistake at the start of the uri, so I wanted to use the `home` button on my keyboard.

This doesn't work, which is completely OK. Normally I would realize it's not ok and just use the arrow-keys instead. But now the input actually got messed up, and hitting backspace caused blocks of text to be removed.

**Comment by Hywan** [comment]
Hello :-),

Can you provide a screenshot please? And do you know what code the “home” key sends?

**Comment by evert** [comment]
I have no idea what the home key sends! But I'm on a small keyboard so I actually just use COMMAND-LEFT to do this.

A screenshot will not be really telling, because when I hit `BACKSPACE` after having used `COMMAND-LEFT`, 8 characters are removed from the input string.

**Comment by evert** [comment]
Actually... never mind, I can't reproduce it anymore :(
