### ISSUE TITLE
Web installer should provide better feedback on error

### ISSUE THREAD

**Issue by evert** [fruux/sabre-katana#224]
note: not intended as high priority, but important before a 1.0 release.

I did the following:

1. "Uninstalled" katana
2. Installed it again on the same mysql database

After doing this the installer just hangs. It should tell me a bit more about the situation =)

**Comment by Hywan** [comment]
Was it fix by https://github.com/fruux/sabre-katana/pull/222?

**Comment by Hywan** [comment]
Can reproduce.
