### ISSUE TITLE
`install.php` should not redirect to `server.php` everytime

### ISSUE THREAD

**Issue by evert** [fruux/sabre-katana#225]
Because the server and installer redirect back and forward in certain situations, it becomes very hard to troubleshoot installation.

Lots of browsers remember redirects, so it's hard to get back to the installer. I think it would be better if the installer could tell me that the installer has already completed, and perhaps provide a link (in a web interface) to the server.

**Comment by Hywan** [comment]
It redirects if no error occured. So there is no back and forward redirection. Only if you are trying to do stuff manually :-). And yes, for us, it's annoying, but not for the end-user.

**Comment by evert** [comment]
We shouldn't just optimize for the situation where no error occurred, but also when there _is_ a problem. We are unlikely to be the only people to need to troubleshoot stuff. So far I've ran into installation bugs 100% of the times I tried installing, just doing stuff regular users would do. The only way I've been able to avoid problems is to avoid certain options =)

So I think it's a good idea to redirect the user _immediately after_ a successful installation, but I think it would be good to not do this if the user manually goes back to the installer.

**Comment by Hywan** [comment]
Manually goes back? So if the user go to `install.php`, we redirect after the installation. Else, if it goes to `server.php` or `admin.php` and is redirected to `install.php`, then we do not redirect?

**Comment by evert** [comment]
I mean this:

1. If a user installed katana for the first time, redirect to admin.php immediately afterwards.
2. If a user _then_ goes back to install.php by explicitly typing the url, don't redirect but show an error saying that installation has already been completed.
