### ISSUE TITLE
[meta] Public directory per user

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-katana#230]
Public means: Everyone could read, only the owner can write. Agree @fruux/developers?

**Comment by evert** [comment]
Great idea!

**Comment by Hywan** [comment]
If we create a `home/<principal>/public/` directory, then we should create a specific node for it with specific ACL, is that correct?

**Comment by evert** [comment]
yes that is correct...

**Comment by evert** [comment]
you actually need to change the node that represents `home/<principal>`, not `home/<principal>/public`, because for the public node you can just `Sabre\DAVACL\FS\Collection`, which actually supports setting the acl via the constructor.

**Comment by Hywan** [comment]
Actually, we have to refine what a public directory is. Yes, any user could read from it, but not list its content. So we have to disable listing.
