### ISSUE TITLE
dependency to incompatible sabre/http version

### ISSUE THREAD

**Issue by mgee** [fruux/sabre-katana#250]
* Setup a fresh installation of `sabre/katana` version: 352f514
* Create a user
* Setup CalDAV syncing for this user [tested with Calendar 8.0 (2034.9) from OSX 10.10.3]

The following error occurs:
```
mod_fcgid: stderr: PHP Fatal error:  Call to undefined function Sabre\\HTTP\\parsePrefer() in /var/www/virtual/myuser/html/katana/vendor/sabre/dav/lib/DAV/Server.php on line 662
```

PHP version: 5.6.6

This happens due to an explicit composer dependency to `sabre/http` `4.0.0alpha1`.

**Comment by Hywan** [comment]
Thanks!
