### ISSUE TITLE
Sexier presentation

### ISSUE THREAD

**Issue by Grummfy** [fruux/sabre-katana#255]
Hi,
most of people don't know what's *DAV protocol, so if you say that sabre-katana is a "A CardDAV, CalDAV and WebDAV ready-to-use server on top of sabre/dav" it's not sexy at all. But with something like this:
It's a synchronisation and management server for your calendar, contact and files builded with open and stardard protocols like CalDav, CardDav, WebDav." it's easier to understand and far more sexy !

**Comment by Hywan** [comment]
Agree!
