### ISSUE TITLE
Home folder missing katana://data/home/

### ISSUE THREAD

**Issue by vonglasow** [fruux/sabre-katana#267]
Hello, with new fresh install, and commit 8b2260f6f57a042a972d113724ecd210fb602b93 on master, I have some trouble to access on "home" folder.

After a git clone, and make install, I run PHP server as explain into the README and when I try to go to 'http://127.0.0.1:8888/install.php' this error appear.

Uncaught exception (Hoa\File\Exception\FileDoesNotExist): Hoa\File\Directory::_open(): (0) Directory katana://data/home/ does not exist. in /tmp/sabre-katana/vendor/hoa/file/Directory.php at line 111.

If I add a "home" folder into "data" everything looks ok.

**Comment by Hywan** [comment]
Hello :-),

Did you install from the archive or from the Git repository?

**Comment by Hywan** [comment]
I found the issue.
