### ISSUE TITLE
Up-to-date Nginx/apache configuration?

### ISSUE THREAD

**Issue by chikamichi** [fruux/sabre-katana#278]
Hi,

Following #226 the example config files for both Nginx and Apache have been removed, due to broken/incorrect settings.

Is there a plan on providing updated versions of those files, with recommended setup? Maybe not as actual files, a simple section within the README and/or the wiki could do the trick.

**Comment by evert** [comment]
Hi @chikamichi,

What are you currently having issues with? Generally the setup for both nginx and apache is: make sure PHP runs and the installer will explain the rest. It should just work with common defaults.

**Comment by Hywan** [comment]
:+1: Nothing particular is required.

**Comment by chikamichi** [comment]
Ok. I'm not familiar with server conf, so I just borrowed from the now deprecated conf files. It may not be needed, but still, here it is:

``` apache
<VirtualHost *:80>
  ServerName sabre.mydomain.tld
  ServerAdmin my@email.tld
  ErrorLog /var/log/apache2/sabre-katana/error.log
  DocumentRoot /home/me/opt/sabre-katana/public/

  <Directory "/home/me/opt/sabre-katana/public/">
    Order deny,allow
    Allow from all
    Require all granted # Apache's new stuff, denies by default nowadays
    DirectoryIndex server.php # I had an Apache error without it

    # This stuff I borrowed, I'm not sure about it:
    RewriteEngine on
    RewriteCond %{SCRIPT_FILENAME} !-f
    RewriteCond %{SCRIPT_FILENAME} !-d
    RewriteRule ^(.*)$ server.php?$1
  </Directory>
</VirtualHost>
```

Is such a conf actually needed?

**Comment by Hywan** [comment]
You don't need the `Rewrite*` stuff.

**Comment by chikamichi** [comment]
Ok, thank you!
