### ISSUE TITLE
Invalid credentials, no matter what - base URL pb?

### ISSUE THREAD

**Issue by chikamichi** [fruux/sabre-katana#279]
Hi,

Once installation is over, after I picked a password for the default "admin" user, no matter what, I can't login (*Invalid credentials / Either username or password is invalid.*) It's happening with both mysql and sqlite. I uninstall/reinstalled (with a drop/re-creation of the database) several time using `make uninstall` / `./bin/katana install`, using different passwords, so I'm pretty sure it's not me mistyping the password :)

I am using the latest version of sabre-katana, on a Debian 8 (jessie) server. No trouble during installation.  With mysql, I'm using a dedicated user (*sabre*) who has all privileges on a *sabre_katana* database.

Any insights?
Thank you.

**Comment by chikamichi** [comment]
Further inspecting the error, I've found that submitting the form triggers a PROPFIND request to http://my.server.tld/server.php/system. The response is a 404:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.0.0</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File not found: server.php in 'root'</s:message>
</d:error>
```

Could it be a problem with my Apache configuration?

**Comment by chikamichi** [comment]
I since fixed my installation using the browser install and #277. I didn't try using the CLI install after I fixed the problem as referenced in #277, but I could if you want, @Hywan.

**Comment by Hywan** [comment]
Did you run the CLI installer with the same user as the project files?

**Comment by chikamichi** [comment]
Yes, same user.

**Comment by synchrone** [comment]
Actually, you must set baseurl to /server.php/ during installation, since it's hardcoded in admin.js.

**Comment by Hywan** [comment]
Still opened?

**Comment by iamfraggle** [comment]
I don't know if my issue is related or not.  My symptom is the same - admin password is always rejected.  Rather than getting a 404 to the PROPFIND though, I'm getting a 501.  I've tried setting up with both CLI and web installers, and with both mysql and sqlite.  Looking in the mysql database there is a user entry with password digest for the admin user.

**Comment by evert** [comment]
@iamfraggle 501 would definitely indicate something else. Make sure you send us the exact HTTP response, including a response body and headers.

**Comment by lkraav** [comment]
I had two errors

* 500 was caused by spelling the directory `/sabre-kitana.git/` instead of `katana`
* 404 was caused by `/sabre-katana.git/` instead of `/sabre-katana.git/public/server.php/`

Fixing those made everything work.

**Comment by controlcde** [comment]
@Hywan Yes, it seams that the problem still exist: If baseurl = "/" than you can´t login.

**Comment by Hywan** [comment]
The path must point to `server.php`, else it does not work.

**Comment by controlcde** [comment]
ok, but if I create some rewrite rules in the web server config I could get pretty urls. Do I have to correct the baseurl in this case, i think so?

**Comment by Hywan** [comment]
I would like to say “yes” but I didn't test this case so far. Your feedback would be very welcome.

**Comment by aciidic** [comment]
I'm struggling with this issue, unable to login via admin.php

I've successfully compiled after installing all requirements, logged in as root via ssh on my VPS running Debian 7.10 x86 with PHP Version 5.6.20-1~dotdeb+7.1

I've used chmod 777 on all files & folders in /var/www/katana but this has not made any difference.

Verbose logging would be really helpful but I have not been able to find any logs, can you advise?

Also, can you please confirm if URI path is absolute or relative?
My installation path is /var/www/katana
I've my URI set to **/var/www/katana/public/server.php/** - is that correct?
(I've tried _/katana/public/server.php/_ and _/public/server.php/_ and _/server.php/_ and _/_ with no luck)

Issue apparent with both cli install and install.php - install is successful but unable to login with credentials. I've tried using .zip download, and also compiled https://github.com/fruux/sabre-katana.git and https://github.com/staabm/sabre-katana.git but issue remains :(

Any advice would be appreciated.

Thanks

**Comment by evert** [comment]
The error you posted indicates that apache is configured to *not* allow webdav methods. Look for `Limit` and `LimitExcept` directives in your apache configuration and adjust them to allow those.

**Comment by aciidic** [comment]
Thanks for the reply Evert. Wish it was documented!

**Comment by evert** [comment]
Glad that that worked though!
