### ISSUE TITLE
Rename 'stub' into something else

### ISSUE THREAD

**Issue by evert** [fruux/sabre-katana#282]
The word `stub` is used throughout the application. I suspect that in most cases where 'stub' is used, it should actually be something like 'package' or 'zip'.

**Comment by Hywan** [comment]
We reuse the same terminology as PHP uses.

**Comment by evert** [comment]
The `stub` in the phar package is _only_ the php file that automatically gets loaded, which doesn't really apply to for example the zip. The term `stub` is not as broad as 'the entire package' or 'the thing that creates the package`, so I feel a better name could be picked here. I'd suggest just calling it 'Packager', but I think we should actually be able to move this all into the `Makefile`. This then also solves #283

**Comment by Hywan** [comment]
Packager is good :smile:.
