### ISSUE TITLE
Can't download a calendar: ({DAV:}read} error

### ISSUE THREAD

**Issue by chikamichi** [fruux/sabre-katana#285]
Hi,

When attempting to download a calendar's .ics, I'm faced with the following error:

``` xml
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>3.0.0</s:sabredav-version>
<s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
<s:message>
User did not have the required privileges ({DAV:}read) for path "calendars/reugny/4430A48C-A629-4F0A-B3C2-A6D86198BB35"
</s:message>
<d:need-privileges>
<d:resource>
<d:href>
/server.php/calendars/reugny/4430A48C-A629-4F0A-B3C2-A6D86198BB35
</d:href>
<d:privilege>
<d:read/>
</d:privilege>
</d:resource>
</d:need-privileges>
</d:error>
```

I sure can connect to sabre/katana's UI, create new users, etc. it's only when fetching a calendar's .ics that it fails in that way.

It's close to something [owncloud experienced a few months ago](https://github.com/owncloud/core/pull/14275), dunno if that's relevant though.

**Comment by evert** [comment]
How are you attempting to download this calendar? The error would indicate that you are trying it with a user that does not have permission to do this.

**Comment by Hywan** [comment]
@chikamichi You have to specify username/password at the HTTP level:
```sh
$ curl --user nick:password …
```
