### ISSUE TITLE
Fix build system

### ISSUE THREAD

**Issue by evert** [fruux/sabre-katana#295]
Currently the build system produces a 140MB zip file and no phar. I'd like to see if this is fixable.

**Comment by Hywan** [comment]
Do you want to ameliorate the `Makefile` targets? We have everything inside. And a PHAR is build :-).

**Comment by evert** [comment]
Hmm... I looked at the Makefile but could not find it there. Just running `make` also didn't do it for me.

**Comment by mgee** [comment]
The 0.4.0 release also contains a folder `build` which contains another `katana_0.4.0.zip` file (~71mb).
Also there is a file `data/configuration/server.json` which leads katana to thinking it is already configured...

These files/folders should probably be excluded when creating the zip file.

**Comment by evert** [comment]
Ah I guess the build system doesn't really make an attempt to do a clean build. I'll try to do another release based on a clean directory today.

**Comment by evert** [comment]
I just put out a 0.4.1 release, that's down to 84 megs and should no longer have any residual configuration. Take a look. This is not a final fix though.

**Comment by mgee** [comment]
Looks good :+1:

**Comment by evert** [comment]
PR #297 addresses this.
