### ISSUE TITLE
REST API?

### ISSUE THREAD

**Issue by C-Duv** [fruux/sabre-katana#296]
Is a REST API planned?

I am looking for a CalDAV (and CardDAV) server that I could "attack"/manage (id. add/edit/delete users/calendars/events/taks/contacts/...) from other applications and Katana seems a great SabreDAV implementation with modern UI.

But I cannot see a place for a REST/SOAP/whatever API (to create/edit accounts, create/edit Calendar/Card events) in the development goals.
For what I have read, you are aiming (mid-close future) to make Katana able to talk to any DAV server and not just SabreDAV, because of that I am not sure a REST API (which might be a little too server-side specific) is in mind.

**Comment by evert** [comment]
CalDAV and CardDAV are bot HTTP apis. In that scenario the katana webapp is a 'client' not a server. It will be 100% static javascript.

So what you need to do, is learn how to integrate with Cal- and CardDAV services. Some more information here:

http://sabre.io/dav/building-a-caldav-client/
http://sabre.io/dav/building-a-carddav-client/

**Comment by C-Duv** [comment]
>  In that scenario the katana webapp is a 'client'.

OK, this is what I though/feared.

What I don't understand is how Katana can create users: there is no "user creation" action in the CalDAV standard right?

**Comment by evert** [comment]
There is not, but for the things that are not standardized, we'll publicly document how this is going to work, so others will have a chance to implement it too.

This currently works by issuing a `MKCOL` request on the `principals` path.

https://github.com/fruux/sabre-katana/blob/master/public/static/javascript/katana-webdav-adapter.js#L99

It's pretty much a standard request. What's new is that the server knows how to create a resource of type `{DAV:}principal`.
