### ISSUE TITLE
Webserver settings to rewrite the a shorter URL

### ISSUE THREAD

**Issue by controlcde** [fruux/sabre-katana#298]
How could I set up katana to get an url like **https://calendar.example.org** and not **https://calendar.example.org/public/server.php/**? Are this a configuration into the webserver (apache2 for example)?

**Comment by evert** [comment]
Only the `public` directory should be shared in apache, not the entire directory tree
For now though I would simply recommend setting up redirects.

We don't officially support url rewriting yet, but we might at one point in the future.
