### ISSUE TITLE
Installation Button doesn't work??

### ISSUE THREAD

**Issue by userwhoami** [fruux/sabre-katana#307]
Hey I tried to install katana, but doesn't matter what i insert the button stays grey and is not clickable. With the enter button the Installation seems to start, but after two hours nothing happed in the progress bar. 
Is there any known issue or where's my failure?

Thanks userwhoami

**Comment by evert** [comment]
If it takes more than 2 seconds, something is definitely wrong. How did you install it? Are you using the zip or from github?

Which PHP version are you using?

**Comment by userwhoami** [comment]
Hey,
i am using PHP 5.5.33 and the zipped Version which i uploaded to my Server via  FTP.

Thanks for your fast answer
Greetings
userwhoami

**Comment by staabm** [comment]
did you check your server/php logs for warnings/errors?

**Comment by userwhoami** [comment]
Not yet, but i'll do as  soon as possible

**Comment by userwhoami** [comment]
[Tue Apr 05 15:51:25 2016] [error] [client 84.187.48.134] PHP Fatal error:  Uncaught exception 'ErrorException' with message 'file_exists(): open_basedir restriction in effect. File(/folders/Data/Library/Hoa/Router/Http.php) is not within the allowed path(s): (/folders/sabre-katana:/tmp)' in /folders//sabre-katana/vendor/hoa/core/Consistency.php:354\nStack trace:\n#0 [internal function]: exception_error_handler(2, 'file_exists(): ...', '/var/customers/...', 354, Array)\n#1 /folders/sabre-katana/vendor/hoa/core/Consistency.php(354): file_exists('/var/customers/...')\n#2 [internal function]: Hoa\\Core\\Consistency\\Consistency::autoload('Hoa\\\\Router\\\\Http')\n#3 /folders/sabre-katana/vendor/hoa/core/Conistency.php(285): spl_autoload_call('Hoa\\\\Router\\\\Http')\n#4 /folders/sabre-katana/vendor/hoa/core/Consistency.php(329): Hoa\\Core\\Consistency\\Consistency->_import('Hoa.Router.Http', true)\n#5 [internal function]: Hoa\\Core\\Consistency\\Consistency::autoload('Hoa\\\\Router\\\\Http')\n#6 /var/u in /folders/sabre-katana/vendor/hoa/core/Consistency.php on line 354, referer: http://LINKTOKATANApublic/install.php


Thats the Error I got. I replaced the folder name and the link, but i changed nothing on the data itself

**Comment by evert** [comment]
Turn off the `open_basedir` setting in your php.ini, restart apache and try again:

http://php.net/manual/en/ini.core.php#ini.open-basedir

**Comment by userwhoami** [comment]
Ok, now it works.
Thanks for your help

userwhoami
