### ISSUE TITLE
Login for other than admin account not possible

### ISSUE THREAD

**Issue by JohRest** [fruux/sabre-katana#308]
I have recently installed the package. Everything works smoothly, without any Problems.

However, if I create any user with username Password, the Login always Fails:

Invalid credentials
Either username or password is invalid.

I've tried countless times to Change usernames and Passwords, but the Response is always the same. If I log on with the admin account that's fine.

does anybody may have an idea what's going on here?

Thanks in advance
Johannes

**Comment by panslaw** [comment]
Hey,

maybe you can try login to admin section? When you create user you can only log in via /server.php.

**Comment by JohRest** [comment]
Hi,
year, I came to the conclusion that the ui is for admin purposes only. I'm using the package without problems until now.

Thanks for answering

Johannes
