### ISSUE TITLE
make: *** [install-client] Error 1

### ISSUE THREAD

**Issue by valodiadeseynes** [fruux/sabre-katana#310]
On Debian Jessie, upon running the 'make install' command during the installation, I get this:

> composer install --no-dev
> Do not run Composer as root/super user! See https://getcomposer.org/root for details
> Loading composer repositories with package information
> Installing dependencies from lock file
>   - Installing hoa/core (2.15.11.09)
>     Loading from cache
> 
>   - Installing hoa/ustring (3.15.11.09)
>     Loading from cache
> 
>   - Installing hoa/stream (0.15.08.28)
>     Loading from cache
> 
>   - Installing hoa/console (2.15.07.27)
>     Loading from cache
> 
>   - Installing hoa/dispatcher (0.15.11.09)
>     Loading from cache
> 
>   - Installing hoa/http (0.15.09.08)
>     Loading from cache
> 
>   - Installing hoa/eventsource (2.15.08.13)
>     Loading from cache
> 
>   - Installing hoa/iterator (1.15.10.29)
>     Loading from cache
> 
>   - Installing hoa/file (0.15.05.27)
>     Loading from cache
> 
>   - Installing hoa/mime (2.15.10.29)
>     Loading from cache
> 
>   - Installing hoa/mail (0.15.10.29)
>     Loading from cache
> 
>   - Installing hoa/router (2.15.10.21)
>     Loading from cache
> 
>   - Installing hoa/socket (0.15.09.08)
>     Loading from cache
> 
>   - Installing hoa/stringbuffer (0.15.09.08)
>     Loading from cache
> 
>   - Installing ircmaxell/password-compat (v1.0.4)
>     Loading from cache
> 
>   - Installing sabre/uri (1.0.1)
>     Loading from cache
> 
>   - Installing sabre/xml (1.2.0)
>     Loading from cache
> 
>   - Installing sabre/vobject (3.4.7)
>     Loading from cache
> 
>   - Installing sabre/event (2.0.2)
>     Loading from cache
> 
>   - Installing sabre/http (4.1.0)
>     Loading from cache
> 
>   - Installing sabre/dav (3.0.5)
>     Loading from cache
> 
> Generating optimized autoload files
> bower install --production
> Makefile:11: recipe for target 'install-client' failed
> make: *** [install-client] Error 1

Then if I go to my install.php page, it tells me:

> Apparently, not all dependencies have been installed.

What can I do?

**Comment by valodiadeseynes** [comment]
Sorry I'm an idiot, I was trying to run the command as root instead of the user. It's solved!

**Comment by Hywan** [comment]
Great! And I am sure you're not an idiot at all :-)!
